name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: fjord_boot_camp_contributors_test
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/fjord_boot_camp_contributors_test"
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          bundler-cache: true
      - name: setup DB
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:schema:load
      - name: Run tests
        run: bundle exec rspec spec/

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Lint Ruby files
        run: bundle exec rubocop -a
      - name: Lint Slim files
        run: bundle exec slim-lint -c config/slim_lint.yml
