name: batch
on:
  schedule:
    - cron: '*/7 * * * *'

jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway
        run: npm i -g @railway/cli
      
      - name: Authenicate the CLI
        run: RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway login --browserless
      
      - name: batch
        run: RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway run bundle exec rails runner lib/batch/contributor_commit_collector.rb

