name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432

    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --path vendor/bundle --without production
          yarn install
      - name: Set env
        run: |
          echo '::set-env name=RAILS_ENV::test'
          echo '::set-env name=DATABASE_URL::postgres://postgres:postgres@localhost:5432/my_database'
      - name: setup DB
        run: |
          bundle exec rails db:schema:load
      - name: Run tests
        run: bundle exec rspec spec/

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Lint Ruby files
        run: bundle exec rubocop -a
      - name: Lint Slim files
        run: bundle exec slim-lint -c config/slim_lint.yml
