name: batch
on:
  schedule:
    - cron: '0 5 10 15 20 25 30 35 40 45 50 55'
jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway
        run: npm i -g @railway/cli
      
      - name: batch
        run: railway run rails runner lib/batch/contributor_commit_collector.rbenv:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
