name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_DB: fjord_boot_camp_contributors_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432

    env:
      RAILS_ENV: test
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Set up database schema
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create
          bundle exec rails db:migrate
      - name: install react
        run: npm install @babel/preset-react
        run: npm install @babel/plugin-syntax-jsx
      - name: Run tests
        run: bundle exec rspec spec/

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Lint Ruby files
        run: bundle exec rubocop -a
      - name: Lint Slim files
        run: bundle exec slim-lint -c config/slim_lint.yml
