name: batch
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway
        run: npm i -g @railway/cli
      
      - name: batch
        run: railway run rails runner lib/batch/contributor_commit_collector.rb
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
